#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Format code first and stage the changes
npm run format
git add .

# Then run linting and type checking
npm run lint
npm run typecheck

# Finally run tests
npm run test
